version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: src/DiscordBot.Api/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    profiles:
      - "dev-bot"

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      - API_URL=api
    profiles:
      - "dev-api"

      