name: Build & Deploy to Dokku

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VERSION: "1.0"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: dokku/${{ secrets.APP_NAME }}:$VERSION
          file: ./DiscordBot.Core/Dockerfile
          context: .
      
      - name: Show docker images
        run: docker images
      
      - name: Save docker image to tar file
        run: docker save dokku/${{ secrets.APP_NAME }}:$VERSION > ${{ secrets.APP_NAME }}.tar
      
      - name: Copy docker image to dokku server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_USERNAME }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_UPLOAD }}
          source: ${{ secrets.APP_NAME }}.tar
          target: .
      
      - name: Load docker image from tar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_USERNAME }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_UPLOAD }}
          script: |
            docker load ${{ secrets.APP_NAME }}.tar
            rm ${{ secrets.APP_NAME }}.tar

      - name: Deploy to dokku
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_USERNAME }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          script: dokku tags:deploy ${{ secrets.APP_NAME }} $VERSION
