name: Build & Deploy to Dokku

# Controls when the action will run. 
on:
  push:
    branches: main
  pull_request:
    
env:
  DEPLOY_BRANCH: "refs/heads/main"
  
jobs:
  conditions:
    runs-on: ubuntu-latest
    outputs:
      deployBranch: ${{ steps.setDeployBranchName.outputs.deployBranch }}
    steps:
      - name: set value
        id: setDeployBranchName
        run: |
          echo "::set-output name=deployBranch::$DEPLOY_BRANCH"  # get top level env and set it as output
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        if: ${{ github.ref == env.DEPLOY_BRANCH }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Bot Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == env.DEPLOY_BRANCH }}
          load: true
          tags: ghcr.io/${{ github.actor }}/${{ secrets.APP_NAME }}:latest
          file: ./src/DiscordBot.Service/Dockerfile
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        
      
  deploy:
   runs-on: ubuntu-latest
   needs: [conditions,main]
   if: ${{ needs.conditions.outputs.deployBranch == github.ref }}
   steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ secrets.APP_NAME }}
          path: .
          
      - name: Copy docker image to dokku server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_USERNAME }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_UPLOAD }}
          source: ${{ secrets.APP_NAME }}.tar
          target: .
      
      - name: Load docker image from tar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_USERNAME }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY_DOCKER_UPLOAD }}
          script: |
            docker load -i ${{ secrets.APP_NAME }}.tar
            rm ${{ secrets.APP_NAME }}.tar

      - name: Deploy to dokku
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_USERNAME }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          script: git:from-image ${{ secrets.APP_NAME }} dokku/${{ secrets.APP_NAME }}:${{ github.sha }}
          
      - name: Run dokku cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_USERNAME }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          script: cleanup
