name: Build & Deploy to Dokku

# Controls when the action will run.
on:
  push:
    branches: main
  pull_request:

env:
  DEPLOY_BRANCH: "refs/heads/main"
  DOCKER_REGISTRY: ghcr.io
  CAPROVER_APP: broyota-bot

jobs:
  conditions:
    runs-on: ubuntu-latest
    outputs:
      deployBranch: ${{ steps.setDeployBranchName.outputs.deployBranch }}
    steps:
      - name: set value
        id: setDeployBranchName
        run: |
          echo "::set-output name=deployBranch::$DEPLOY_BRANCH"  # get top level env and set it as output
  main:
    needs: [conditions]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set docker image names
        run: |
          export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/${{ github.actor }}/${{ env.CAPROVER_APP }}
          echo $IMAGE_NAME_WITH_REGISTRY >> $GITHUB_ENV
          echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:latest" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ needs.conditions.outputs.deployBranch == github.ref }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Bot Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: ${{ needs.conditions.outputs.deployBranch == github.ref }}
          load: true
          tags: ${{ env.FULL_IMAGE_NAME }}
          file: ./src/DiscordBot.Service/Dockerfile
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [conditions, main]
    if: ${{ needs.conditions.outputs.deployBranch == github.ref }}
    steps:
      - name: Deploy to caprover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          # todo: Add caprover server to secrets
          server: ${{ secrets.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          # todo: add caprover token to secrets
          token: '${{ secrets.CAPROVER_APP_TOKEN }}'
          image: '${{ env.FULL_IMAGE_NAME }}'
